### ISSUE TITLE
I reopen #27: Still issues errors to compile & build & run this app on iOS

### ISSUE THREAD

**Issue by cerkut** [xamarin/xamarin-store-app#62]
See https://github.com/xamarin/xamarin-store-app/issues/27

Here is my experience: Even after accepting (unmentioned) Indie license, there are too many build options, and  many of them terminate with an error. For example: AppStore | iPhone gives (see the screenshot):

... /Developer/xamarin/xamarin-store-app/XamarinStore.iOS/MTOUCHTASK: Error MT2002: Failed to resolve "CoreGraphics.CGSize Foundation.NSString::StringSize(UIKit.UIFont,CoreGraphics.CGSize)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=[REMOVEDforThisIssue@GITHUB]" (MT2002) (XamarinStore.iOS)

Also note the run options are deselected. I can compile & run, e.g., Tasky fine, but find the instructions & options too much for an app that aims to demonstrate how easy the things are! 

Please add to instructions the license condition, and build targets and running instructions.

![ed95c777-f1a2-4056-945f-01e160df4c43](https://cloud.githubusercontent.com/assets/1277203/5891091/6f5d4f50-a481-11e4-97c1-bc02840312f0.png)

**Comment by jamesmontemagno** [comment]
I am sorry, I have fixes this today. Please re-sync this. 

Simply select "Debug" as your option, and make the iOS project your startup.
![image](https://cloud.githubusercontent.com/assets/1676321/5909256/b35f314a-a563-11e4-801e-e04a8b4643ea.png)

**Comment by cerkut** [comment]
Works indeed, thanks.
